---
niri_kdl_outputs: {}
  # "HDMI-A-2": |-
  #   position x=0 y=0
  # "HDMI-A-1": |-
  #   position x=2560 y=0
  # "Dell Inc. DELL U2722DE 4SR7GH3": |-
  #   position x=0 y=0
  # "Dell Inc. DELL U2722DE 2NR7GH3": |-
  #   position x=2560 y=0
  # "Chimei Innolux Corporation 0x160A Unknown": |-
  #   position x=5120 y=0

sddm_custom_compositor_config: |-
  /-output "HDMI-A-2" {
      position x=0 y=0
  }

  /-output "HDMI-A-1" {
      position x=2560 y=0
  }

  /-output "Dell Inc. DELL U2722DE 4SR7GH3" {
      position x=0 y=0
  }

  /-output "Dell Inc. DELL U2722DE 2NR7GH3" {
      position x=2560 y=0
  }

  /-output "Chimei Innolux Corporation 0x160A Unknown" {
      position x=5120 y=0
  }
