---
apps_pkgs:
  1password: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
  google-chrome-stable: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  slack: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.47.69/slack-4.47.69-0.1.el8.x86_64.rpm
  zoom: https://zoom.us/client/latest/zoom_x86_64.rpm

apps_special_extra:
  - joplin
