---
apps_packages:
  - acl
  - bind-utils
  - btop
  - cascadia-fonts-all
  - code
  - cifs-utils
  - docker-compose
  - evolution-ews
  - firefox
  - freerdp
  - git
  - gnome-calculator
  - iwlwifi-mvm-firmware
  - kitty
  - opensc
  - openssl
  - pciutils
  - podman-docker
  - python3-libselinux
  - terminus-fonts-console
  - usbutils
  - vim-default-editor

apps_repos:
  code:
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

# add apps_special_tailscale_authkey if you want to start the tailnet
# do not place this in git -- it's a password!
apps_special:
  - tailscale
  - uv
